### ISSUE TITLE
error replotting family figures

### ISSUE THREAD

**Issue by fontiela** [ahotovec/REDPy#24]
when REDPy start creating plots I get get the following error:
```
...
Length of Orphan table: 212
Number of repeaters: 435
Number of clusters: 22
Creating plots...
Traceback (most recent call last):
  File "catfill.py", line 136, in <module>
    redpy.plotting.createPlots(rtable, ftable, ttable, ctable, otable, opt)
  File "/Users/joaofontiela/geophysics/REDPy/redpy/plotting.py", line 75, in createPlots
    plotFamilies(rtable, ftable, ctable, opt)
  File "/Users/joaofontiela/geophysics/REDPy/redpy/plotting.py", line 1094, in plotFamilies
    fi, ids, id1, id2, ccc, 'png', 100, cnum, 0, 0, opt)
  File "/Users/joaofontiela/geophysics/REDPy/redpy/plotting.py", line 1269, in plotSingleFamily
    ymin = 0.5*np.min(windowAmp[np.nonzero(windowAmp)])
  File "<__array_function__ internals>", line 6, in amin
  File "/Users/joaofontiela/opt/anaconda3/envs/redpy/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2880, in amin
    keepdims=keepdims, initial=initial, where=where)
  File "/Users/joaofontiela/opt/anaconda3/envs/redpy/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity
Closing remaining open files:SaoJorge_2023.h5...done
```

Then, I force re-plot family figures with ```python forcePlot.py -f -c settings_saojorge2023.cfg```and got another error:
```
Traceback (most recent call last):
  File "forcePlot.py", line 91, in <module>
    redpy.plotting.plotFamilies(rtable, ftable, ctable, opt)
  File "/Users/joaofontiela/geophysics/REDPy/redpy/plotting.py", line 1094, in plotFamilies
    fi, ids, id1, id2, ccc, 'png', 100, cnum, 0, 0, opt)
  File "/Users/joaofontiela/geophysics/REDPy/redpy/plotting.py", line 1269, in plotSingleFamily
    ymin = 0.5*np.min(windowAmp[np.nonzero(windowAmp)])
  File "<__array_function__ internals>", line 6, in amin
  File "/Users/joaofontiela/opt/anaconda3/envs/redpy/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2880, in amin
    keepdims=keepdims, initial=initial, where=where)
  File "/Users/joaofontiela/opt/anaconda3/envs/redpy/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity
```
Rendering html files with command ```python forcePlot.py -l -c settings_saojorge2023.cfg ``` works fine.

It's the first time I'm facing this problem with REDPy. Last days, I had to clone last branch of REDPy due to several errors. Likely the error were caused by the ```cfg``` than the code.

**Comment by ahotovec** [comment]
I feel like I've had this issue before as well. Try changing "printsta" in your .cfg file. If this is related to your other issue where data are not being found, it's possible you have chosen a channel that doesn't have any non-zero amplitude data. Let me know if that works, and I'll try to add some error handling for it.

**Comment by fontiela** [comment]
I tested with a run that worked on the past and REDPy plot everything correctly with no complains. Problem should be related with my dataset or with the settings. I let you my progresses.

**Comment by fontiela** [comment]
Problem was related with stations number in ```printsta```.  After changing the parameter, it's working fine.
