### ISSUE TITLE
Version of bokeh raises conflict

### ISSUE THREAD

**Issue by mhoareau** [ahotovec/REDPy#6]
When trying to install with the documentation :

`conda install -c obspy obspy pytables pandas basemap bokeh=0.9.3 mock nose PIL`

It raises a conflict error :
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - basemap
  - bokeh 0.9.3*
  - navigator-updater
Use "conda info <package>" to see the dependencies for each package.
```

It works when installing the last version of bokeh (0.12.5) but then, there is an error when trying the Lapine exemple when the script tries to update the plots :
```
2015-10-28T23:00:00.000000Z
Length of Orphan table: 327
Number of repeaters: 182
Number of clusters: 11
Time spent this iteration: 0.0916738351186 minutes
Caught up to: 2015-10-28T23:58:58.560000Z
Updating plots...
Traceback (most recent call last):
  File "backfill.py", line 169, in <module>
    redpy.plotting.createPlots(rtable, ftable, ttable, ctable, opt)
  File "/home/mhoareau/Logiciels/REDPy/redpy/plotting.py", line 35, in createPlots
    plotTimelines(rtable, ftable, ttable, opt)
  File "/home/mhoareau/Logiciels/REDPy/redpy/plotting.py", line 91, in plotTimelines
    o0.title = 'Repeaters vs. Orphans by {:.1f} Hour Bin'.format(opt.dybin*24)
  File "/home/mhoareau/anaconda2/lib/python2.7/site-packages/bokeh/core/has_props.py", line 269, in __setattr__
    super(HasProps, self).__setattr__(name, value)
  File "/home/mhoareau/anaconda2/lib/python2.7/site-packages/bokeh/core/property/descriptors.py", line 495, in __set__
    self._internal_set(obj, value, setter)
  File "/home/mhoareau/anaconda2/lib/python2.7/site-packages/bokeh/core/property/descriptors.py", line 710, in _internal_set
    value = self.property.prepare_value(obj, self.name, value)
  File "/home/mhoareau/anaconda2/lib/python2.7/site-packages/bokeh/core/property/bases.py", line 265, in prepare_value
    raise e
ValueError: expected an instance of type Title, got Repeaters vs. Orphans by 3.0 Hour Bin of type str
Closing remaining open files:LPtest.h5...done
```

Any help would be very appreciated :)

**Comment by ahotovec** [comment]
Mickaël, I'll see if I can reproduce the error and try to track down the problem. Would you mind also copying your output of `conda list`?

**Comment by ahotovec** [comment]
Also, is this error raised when you run the default example (not Lapine)?

**Comment by mhoareau** [comment]
Yes, same error with the default example.

```
21:05 $ python catfill.py mshcat.csv
Traceback (most recent call last):
  File "catfill.py", line 133, in <module>
    redpy.plotting.createPlots(rtable, ftable, ttable, ctable, opt)
  File "/home/mhoareau/Logiciels/REDPy/redpy/plotting.py", line 35, in createPlots
    plotTimelines(rtable, ftable, ttable, opt)
  File "/home/mhoareau/Logiciels/REDPy/redpy/plotting.py", line 89, in plotTimelines
    o0.title = 'Repeaters vs. Orphans by {:.1f} Day Bin'.format(opt.dybin)
  File "/home/mhoareau/anaconda2/lib/python2.7/site-packages/bokeh/core/has_props.py", line 269, in __setattr__
    super(HasProps, self).__setattr__(name, value)
  File "/home/mhoareau/anaconda2/lib/python2.7/site-packages/bokeh/core/property/descriptors.py", line 495, in __set__
    self._internal_set(obj, value, setter)
  File "/home/mhoareau/anaconda2/lib/python2.7/site-packages/bokeh/core/property/descriptors.py", line 710, in _internal_set
    value = self.property.prepare_value(obj, self.name, value)
  File "/home/mhoareau/anaconda2/lib/python2.7/site-packages/bokeh/core/property/bases.py", line 265, in prepare_value
    raise e
ValueError: expected an instance of type Title, got Repeaters vs. Orphans by 1.0 Day Bin of type str
Closing remaining open files:redpytable.h5...done

```

**Comment by ahotovec** [comment]
Mickaël, I reinstalled this on a clean virtual environment on my computer and it runs without error. My suspicion is that we're running into some sort of dependency conflict in your python environment. Here is the output of my `conda list`:

```
# packages in environment at /Users/ahotovecellis/anaconda/envs/redpytest:
#
appnope                   0.1.0                    py27_0  
backports                 1.0                      py27_0  
backports_abc             0.5                      py27_0  
basemap                   1.0.7                np19py27_0  
bokeh                     0.9.3                np19py27_0  
colorama                  0.3.9                    py27_0  
decorator                 4.0.11                   py27_0  
enum34                    1.1.6                    py27_0  
flask                     0.10.1                   py27_2  
freetype                  2.5.5                         1  
funcsigs                  1.0.2                    py27_0  
future                    0.16.0                   py27_1  
geos                      3.3.3                         0  
get_terminal_size         1.0.0                    py27_0  
gevent                    1.0.1                    py27_0  
gevent-websocket          0.9.3                    py27_0  
greenlet                  0.4.12                   py27_0  
hdf5                      1.8.15.1                      2  
ipython                   5.3.0                    py27_0  
ipython_genutils          0.2.0                    py27_0  
itsdangerous              0.24                     py27_0  
jinja2                    2.9.6                    py27_0  
jpeg                      8d                            2  
lcms                      1.19                          0  
libiconv                  1.14                          0  
libpng                    1.6.17                        0  
libxml2                   2.9.4                         0  
libxslt                   1.1.29                        0  
lxml                      3.8.0                    py27_0  
markupsafe                0.23                     py27_2  
matplotlib                1.4.3                np19py27_3  
mkl                       11.3.3                        0  
mock                      2.0.0                    py27_0  
nose                      1.3.7                    py27_1  
numexpr                   2.4.4                np19py27_0  
numpy                     1.9.3                    py27_3  
obspy                     1.0.2                    py27_0    obspy
openssl                   1.0.2l                        0  
pandas                    0.16.2               np19py27_0  
path.py                   10.3.1                   py27_0  
pathlib2                  2.2.1                    py27_0  
pbr                       1.10.0                   py27_0  
pexpect                   4.2.1                    py27_0  
pickleshare               0.7.4                    py27_0  
pil                       1.1.7                    py27_2  
pip                       9.0.1                    py27_1  
prompt_toolkit            1.0.14                   py27_0  
ptyprocess                0.5.1                    py27_0  
pygments                  2.2.0                    py27_0  
pyparsing                 2.0.3                    py27_0  
pyqt                      4.11.4                   py27_4  
pytables                  3.2.2                np19py27_0  
python                    2.7.13                        0  
python-dateutil           2.6.0                    py27_0  
pytz                      2017.2                   py27_0  
pyyaml                    3.12                     py27_0  
pyzmq                     14.7.0                   py27_1  
qt                        4.8.7                         4  
readline                  6.2                           2  
requests                  2.14.2                   py27_0  
scandir                   1.5                      py27_0  
scipy                     0.17.1               np19py27_1  
setuptools                27.2.0                   py27_0  
simplegeneric             0.8.1                    py27_1  
singledispatch            3.4.0.3                  py27_0  
sip                       4.18                     py27_0  
six                       1.10.0                   py27_0  
sqlalchemy                1.1.10                   py27_0  
sqlite                    3.13.0                        0  
ssl_match_hostname        3.4.0.2                  py27_1  
tk                        8.5.18                        0  
tornado                   4.5.1                    py27_0  
traitlets                 4.3.2                    py27_0  
ujson                     1.33                     py27_0  
wcwidth                   0.1.7                    py27_0  
werkzeug                  0.12.2                   py27_0  
wheel                     0.29.0                   py27_0  
yaml                      0.1.6                         0  
zeromq                    4.1.3                         0  
zlib                      1.2.8                         3  
```

**Comment by mhoareau** [comment]
Thanks for trying :)
I will retry from scratch and let you know

**Comment by mhoareau** [comment]
Sorry, I forgot to send the output of `conda list`

```
11:37 $ conda list
# packages in environment at /home/mhoareau/anaconda2:
#
_license                  1.1                      py27_1  
alabaster                 0.7.10                   py27_0  
anaconda                  custom                   py27_0  
anaconda-client           1.6.3                    py27_0  
anaconda-navigator        1.6.2                    py27_0  
anaconda-project          0.6.0                    py27_0  
asn1crypto                0.22.0                   py27_0  
astroid                   1.4.9                    py27_0  
astropy                   1.3.2               np112py27_0  
babel                     2.4.0                    py27_0  
backports                 1.0                      py27_0  
backports_abc             0.5                      py27_0  
basemap                   1.0.7               np112py27_0  
beautifulsoup4            4.6.0                    py27_0  
bitarray                  0.8.1                    py27_0  
blaze                     0.10.1                   py27_0  
bleach                    1.5.0                    py27_0  
bokeh                     0.12.5                   py27_1  
boto                      2.46.1                   py27_0  
bottleneck                1.2.1               np112py27_0  
cairo                     1.14.8                        0  
cdecimal                  2.3                      py27_2  
cffi                      1.10.0                   py27_0  
chardet                   3.0.3                    py27_0  
click                     6.7                      py27_0  
cloudpickle               0.2.2                    py27_0  
clyent                    1.2.2                    py27_0  
colorama                  0.3.9                    py27_0  
conda                     4.3.21                   py27_0  
conda-env                 2.6.0                         0  
configparser              3.5.0                    py27_0  
contextlib2               0.5.5                    py27_0  
cryptography              1.8.1                    py27_0  
curl                      7.52.1                        0  
cycler                    0.10.0                   py27_0  
cython                    0.25.2                   py27_0  
cytoolz                   0.8.2                    py27_0  
dask                      0.14.3                   py27_1  
datashape                 0.5.4                    py27_0  
dbus                      1.10.10                       0  
decorator                 4.0.11                   py27_0  
distributed               1.16.3                   py27_0  
docutils                  0.13.1                   py27_0  
entrypoints               0.2.2                    py27_1  
enum34                    1.1.6                    py27_0  
et_xmlfile                1.0.1                    py27_0  
expat                     2.1.0                         0  
fastcache                 1.0.2                    py27_1  
flask                     0.12.2                   py27_0  
flask-cors                3.0.2                    py27_0  
fontconfig                2.12.1                        3  
freetype                  2.5.5                         2  
funcsigs                  1.0.2                    py27_0  
functools32               3.2.3.2                  py27_0  
future                    0.16.0                   py27_1  
futures                   3.1.1                    py27_0  
geos                      3.5.0                         0  
get_terminal_size         1.0.0                    py27_0  
gevent                    1.2.1                    py27_0  
glib                      2.50.2                        1  
greenlet                  0.4.12                   py27_0  
grin                      1.2.1                    py27_3  
gst-plugins-base          1.8.0                         0  
gstreamer                 1.8.0                         0  
h5py                      2.7.0               np112py27_0  
harfbuzz                  0.9.39                        2  
hdf5                      1.8.17                        1  
heapdict                  1.0.0                    py27_1  
html5lib                  0.999                    py27_0  
icu                       54.1                          0  
idna                      2.5                      py27_0  
imagesize                 0.7.1                    py27_0  
ipaddress                 1.0.18                   py27_0  
ipykernel                 4.6.1                    py27_0  
ipython                   5.3.0                    py27_0  
ipython_genutils          0.2.0                    py27_0  
ipywidgets                6.0.0                    py27_0  
isort                     4.2.5                    py27_0  
itsdangerous              0.24                     py27_0  
jbig                      2.1                           0  
jdcal                     1.3                      py27_0  
jedi                      0.10.2                   py27_2  
jinja2                    2.9.6                    py27_0  
jpeg                      8d                            2  
jsonschema                2.6.0                    py27_0  
jupyter                   1.0.0                    py27_3  
jupyter_client            5.0.1                    py27_0  
jupyter_console           5.1.0                    py27_0  
jupyter_core              4.3.0                    py27_0  
lazy-object-proxy         1.2.2                    py27_0  
lcms                      1.19                          0  
libffi                    3.2.1                         1  
libgcc                    4.8.5                         2  
libgfortran               3.0.0                         1  
libiconv                  1.14                          0  
libpng                    1.6.27                        0  
libsodium                 1.0.10                        0  
libtiff                   4.0.6                         2  
libtool                   2.4.2                         0  
libxcb                    1.12                          1  
libxml2                   2.9.4                         0  
libxslt                   1.1.29                        0  
llvmlite                  0.18.0                   py27_0  
locket                    0.2.0                    py27_1  
lxml                      3.7.3                    py27_0  
markupsafe                0.23                     py27_2  
matplotlib                2.0.2               np112py27_0  
mistune                   0.7.4                    py27_0  
mkl                       2017.0.1                      0  
mkl-service               1.1.2                    py27_3  
mock                      2.0.0                    py27_0  
mpmath                    0.19                     py27_1  
msgpack-python            0.4.8                    py27_0  
multipledispatch          0.4.9                    py27_0  
navigator-updater         0.1.0                    py27_0  
nbconvert                 5.1.1                    py27_0  
nbformat                  4.3.0                    py27_0  
networkx                  1.11                     py27_0  
nltk                      3.2.3                    py27_0  
nose                      1.3.7                    py27_1  
notebook                  5.0.0                    py27_0  
numba                     0.33.0              np112py27_0  
numexpr                   2.6.2               np112py27_0  
numpy                     1.12.1                   py27_0  
numpydoc                  0.6.0                    py27_0  
obspy                     1.0.2                    py27_0    obspy
odo                       0.5.0                    py27_1  
olefile                   0.44                     py27_0  
openpyxl                  2.4.7                    py27_0  
openssl                   1.0.2l                        0  
packaging                 16.8                     py27_0  
pandas                    0.20.1              np112py27_0  
pandocfilters             1.4.1                    py27_0  
pango                     1.40.3                        1  
partd                     0.3.8                    py27_0  
path.py                   10.3.1                   py27_0  
pathlib2                  2.2.1                    py27_0  
patsy                     0.4.1                    py27_0  
pbr                       1.10.0                   py27_0  
pcre                      8.39                          1  
pep8                      1.7.0                    py27_0  
pexpect                   4.2.1                    py27_0  
pickleshare               0.7.4                    py27_0  
pil                       1.1.7                    py27_2  
pillow                    3.4.2                    py27_0  
pip                       9.0.1                    py27_1  
pixman                    0.34.0                        0  
ply                       3.10                     py27_0  
prompt_toolkit            1.0.14                   py27_0  
psutil                    5.2.2                    py27_0  
ptyprocess                0.5.1                    py27_0  
py                        1.4.33                   py27_0  
pycairo                   1.10.0                   py27_0  
pycosat                   0.6.2                    py27_0  
pycparser                 2.17                     py27_0  
pycrypto                  2.6.1                    py27_6  
pycurl                    7.43.0                   py27_2  
pyflakes                  1.5.0                    py27_0  
pygments                  2.2.0                    py27_0  
pylint                    1.6.4                    py27_1  
pyodbc                    4.0.16                   py27_0  
pyopenssl                 17.0.0                   py27_0  
pyparsing                 2.1.4                    py27_0  
pyqt                      5.6.0                    py27_2  
pytables                  3.3.0               np112py27_0  
pytest                    3.0.7                    py27_0  
python                    2.7.13                        0  
python-dateutil           2.6.0                    py27_0  
pytz                      2017.2                   py27_0  
pywavelets                0.5.2               np112py27_0  
pyyaml                    3.12                     py27_0  
pyzmq                     16.0.2                   py27_0  
qt                        5.6.2                         2  
qtawesome                 0.4.4                    py27_0  
qtconsole                 4.3.0                    py27_0  
qtpy                      1.2.1                    py27_0  
readline                  6.2                           2  
requests                  2.14.2                   py27_0  
rope                      0.9.4                    py27_1  
ruamel_yaml               0.11.14                  py27_1  
scandir                   1.5                      py27_0  
scikit-image              0.13.0              np112py27_0  
scikit-learn              0.18.1              np112py27_1  
scipy                     0.19.0              np112py27_0  
seaborn                   0.7.1                    py27_0  
setuptools                27.2.0                   py27_0  
simplegeneric             0.8.1                    py27_1  
singledispatch            3.4.0.3                  py27_0  
sip                       4.18                     py27_0  
six                       1.10.0                   py27_0  
snowballstemmer           1.2.1                    py27_0  
sortedcollections         0.5.3                    py27_0  
sortedcontainers          1.5.7                    py27_0  
sphinx                    1.5.6                    py27_0  
spyder                    3.1.4                    py27_0  
sqlalchemy                1.1.9                    py27_0  
sqlite                    3.13.0                        0  
ssl_match_hostname        3.4.0.2                  py27_1  
statsmodels               0.8.0               np112py27_0  
subprocess32              3.2.7                    py27_0  
sympy                     1.0                      py27_0  
tblib                     1.3.2                    py27_0  
terminado                 0.6                      py27_0  
testpath                  0.3                      py27_0  
tk                        8.5.18                        0  
toolz                     0.8.2                    py27_0  
tornado                   4.5.1                    py27_0  
traitlets                 4.3.2                    py27_0  
unicodecsv                0.14.1                   py27_0  
unixodbc                  2.3.4                         0  
wcwidth                   0.1.7                    py27_0  
werkzeug                  0.12.2                   py27_0  
wheel                     0.29.0                   py27_0  
widgetsnbextension        2.0.0                    py27_0  
wrapt                     1.10.10                  py27_0  
xlrd                      1.0.0                    py27_0  
xlsxwriter                0.9.6                    py27_0  
xlwt                      1.2.0                    py27_0  
xz                        5.2.2                         1  
yaml                      0.1.6                         0  
zeromq                    4.1.5                         0  
zict                      0.1.2                    py27_0  
zlib                      1.2.8                         3 
```

**Comment by ahotovec** [comment]
Ah, I see after re-reading your initial comment and then your `conda list` that indeed, we have different versions of bokeh. I had to freeze the requirement at v0.9 because they changed the way things were handled in v0.10+ and I'd basically have to rewrite huge portions of the bokeh-related code to make it work again. Until I rewrite those sections, perhaps the best thing to do would be to install redpy in a virtual environment so it doesn't mess with any other python codes you have.

**Comment by ahotovec** [comment]
I've _finally_ updated the bokeh requirements to 0.10+ (works now with bokeh's latest release (as of this comment) v0.12.14). Other requirements have been changed, but they should be more streamlined now.
